name: Build and Push RAG URLs Worker Docker image to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
      - name: Fetch latest upstream commit SHA
        id: upstream_sha
        run: |
          SHA=$(git ls-remote https://github.com/rowboatlabs/rowboat HEAD | awk '{print $1}')
          SHORT_SHA=${SHA:0:7}
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Check if image with short SHA exists in GHCR
        id: check_image
        env:
          GHCR_REPO: ghcr.io/${{ github.repository_owner }}/rag-urls-worker
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ steps.upstream_sha.outputs.short_sha }}
          REPO=${{ github.repository_owner }}/rag-urls-worker
          EXISTS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://ghcr.io/v2/$REPO/manifests/$TAG" | grep -c 'errors')
          if [ "$EXISTS" = "0" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Rowboat repository
        uses: actions/checkout@v4
        with:
          repository: rowboatlabs/rowboat

      - name: Log in to GitHub Container Registry
        if: steps.check_image.outputs.exists == 'false'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (for multi-arch builds)
        if: steps.check_image.outputs.exists == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.check_image.outputs.exists == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (multi-arch, tagged with SHA)
        if: steps.check_image.outputs.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: ./apps/rowboat
          file: scripts.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rag-urls-worker:latest
            ghcr.io/${{ github.repository_owner }}/rag-urls-worker:${{ steps.upstream_sha.outputs.short_sha }}
          build-args: |
            UPSTREAM_SHA=${{ steps.upstream_sha.outputs.sha }}
          platforms: linux/amd64,linux/arm64
          provenance: true
          sbom: true

      - name: Run Trivy vulnerability scanner
        if: steps.check_image.outputs.exists == 'false'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/rag-urls-worker:${{ steps.upstream_sha.outputs.short_sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
  
      - name: Upload Trivy scan results to GitHub Security tab
        if: steps.check_image.outputs.exists == 'false'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'container-security'
